# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AltName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.PositiveIntegerField(db_index=True)),
                ('language', models.CharField(max_length=6)),
                ('crc', models.CharField(db_index=True, default='', max_length=200)),
                ('url', models.CharField(db_index=True, default='', max_length=100)),
                ('name', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'country'), (2, 'region'), (3, 'city')])),
                ('is_main', models.BooleanField(default=False)),
                ('is_preferred', models.BooleanField(default=False)),
                ('is_short', models.BooleanField(default=False)),
                ('is_colloquial', models.BooleanField(default=False)),
                ('is_historic', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['crc'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('timezone', models.CharField(default='', max_length=40)),
                ('population', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('tld', models.CharField(default='', max_length=2)),
                ('continent', models.CharField(default='', max_length=2)),
                ('population', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('country', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtrcity.Country')),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtrcity.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtrcity.Region'),
        ),
        migrations.AddField(
            model_name='altname',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtrcity.Country'),
        ),
        migrations.AddField(
            model_name='altname',
            name='region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtrcity.Region'),
        ),
        migrations.AlterIndexTogether(
            name='city',
            index_together=set([('lat', 'lng')]),
        ),
        migrations.AlterIndexTogether(
            name='altname',
            index_together=set([('language', 'crc', 'is_main'), ('geoname_id', 'language', 'is_main')]),
        ),
    ]
